import 'package:fruts/src/data/uuid.dart';
import 'package:fruts/src/models/category.dart';
import 'package:fruts/src/models/plant.dart';
import 'package:fruts/src/models/nutrition_type.dart';

class Plants {
  static List<Plant> values = <Plant>[
    // Exotics
    Plant(
      id: Uuid.v4(),
      name: 'Ackee',
      genus: 'Blighia',
      category: Category.exotics,
      nutritions: [
        {NutritionType.carbohydates: 11.0},
        {NutritionType.protein: 4.0},
        {NutritionType.fat: 9.0},
        {NutritionType.calories: 140.0},
        {NutritionType.sugar: 4.0},
      ],
      price: 1.99,
      image: 'images/exotics/ackee.png',
      rating: 4.7,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Chayote',
      genus: 'Sechium',
      category: Category.exotics,
      nutritions: [
        {NutritionType.carbohydates: 4.0},
        {NutritionType.protein: 0.0},
        {NutritionType.fat: 0.0},
        {NutritionType.calories: 19.0},
        {NutritionType.sugar: 1.0},
      ],
      price: 1.99,
      image: 'images/exotics/chayote.png',
      rating: 3.4,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Durian',
      genus: 'Durio',
      category: Category.exotics,
      nutritions: [
        {NutritionType.carbohydates: 41.0},
        {NutritionType.protein: 4.0},
        {NutritionType.fat: 5.0},
        {NutritionType.calories: 220.0},
        {NutritionType.sugar: 32.3},
      ],
      price: 49.99,
      image: 'images/exotics/durian.png',
      rating: 1.2,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Rambutan',
      genus: 'Nephelium',
      category: Category.exotics,
      nutritions: [
        {NutritionType.carbohydates: 10.0},
        {NutritionType.protein: 3.0},
        {NutritionType.fat: 2.0},
        {NutritionType.calories: 69.0},
        {NutritionType.sugar: 0.0},
      ],
      price: 0.99,
      image: 'images/exotics/rambutan.png',
      rating: 4.3,
    ),

    // Fresh
    Plant(
      id: Uuid.v4(),
      name: 'Corn',
      genus: 'Zea',
      category: Category.fresh,
      nutritions: [
        {NutritionType.carbohydates: 21.0},
        {NutritionType.protein: 3.0},
        {NutritionType.fat: 1.0},
        {NutritionType.calories: 100.0},
        {NutritionType.sugar: 5.0},
      ],
      price: 3.59,
      image: 'images/fresh/corn.PNG',
      rating: 4.2,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Cucumber',
      genus: 'Cucumis',
      category: Category.fresh,
      nutritions: [
        {NutritionType.carbohydates: 3.0},
        {NutritionType.protein: 0.0},
        {NutritionType.fat: 0.0},
        {NutritionType.calories: 15.0},
        {NutritionType.sugar: 1.0},
      ],
      price: 3.99,
      image: 'images/fresh/cucumber.PNG',
      rating: 4.0,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Eggplant',
      genus: 'Nightshade',
      category: Category.fresh,
      nutritions: [
        {NutritionType.carbohydates: 8.0},
        {NutritionType.protein: 1.0},
        {NutritionType.fat: 0.0},
        {NutritionType.calories: 33.0},
        {NutritionType.sugar: 3.0},
      ],
      price: 4.99,
      image: 'images/fresh/egg-plant.PNG',
      rating: 3.5,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Garlis',
      genus: 'Onions',
      category: Category.fresh,
      nutritions: [
        {NutritionType.carbohydates: 33.0},
        {NutritionType.protein: 6.0},
        {NutritionType.fat: 0.0},
        {NutritionType.calories: 149.0},
        {NutritionType.sugar: 1.0},
      ],
      price: 2.99,
      image: 'images/fresh/garlic.PNG',
      rating: 3.0,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Red ',
      genus: 'Capsicum',
      category: Category.fresh,
      nutritions: [
        {NutritionType.carbohydates: 4.0},
        {NutritionType.protein: 1.0},
        {NutritionType.fat: 0.0},
        {NutritionType.calories: 31.0},
        {NutritionType.sugar: 4.0},
      ],
      price: 3.49,
      image: 'images/fresh/red-pepper.PNG',
      rating: 2.0,
    ),

    // Fruits
    Plant(
      id: Uuid.v4(),
      name: 'Apple',
      genus: 'Malus',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 11.4},
        {NutritionType.protein: 0.3},
        {NutritionType.fat: 0.4},
        {NutritionType.calories: 52.0},
        {NutritionType.sugar: 10.3},
      ],
      price: 2.99,
      image: 'images/fruits/apple.PNG',
      rating: 4.2,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Avocado',
      genus: 'Bay',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 8.0},
        {NutritionType.protein: 2.0},
        {NutritionType.fat: 14.0},
        {NutritionType.calories: 160.0},
        {NutritionType.sugar: 0.0},
      ],
      price: 2.99,
      image: 'images/fruits/avocado.PNG',
      rating: 3.7,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Banana',
      genus: 'Musa',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 22.0},
        {NutritionType.protein: 1.0},
        {NutritionType.fat: 0.2},
        {NutritionType.calories: 96.0},
        {NutritionType.sugar: 17.2},
      ],
      price: 4.99,
      image: 'images/fruits/banana.PNG',
      rating: 4.3,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Blueberry',
      genus: 'Fragaria',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 5.5},
        {NutritionType.protein: 0.0},
        {NutritionType.fat: 0.4},
        {NutritionType.calories: 29.0},
        {NutritionType.sugar: 5.4},
      ],
      price: 5.99,
      image: 'images/fruits/blueberry.png',
      rating: 4.6,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Cherry',
      genus: 'Prunus',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 10.0},
        {NutritionType.protein: 1.0},
        {NutritionType.fat: 0.3},
        {NutritionType.calories: 50.0},
        {NutritionType.sugar: 8.0},
      ],
      price: 4.49,
      image: 'images/fruits/cherry.png',
      rating: 4.6,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Lemon',
      genus: 'Citrus',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 9.0},
        {NutritionType.protein: 0.1},
        {NutritionType.fat: 0.3},
        {NutritionType.calories: 29.0},
        {NutritionType.sugar: 2.5},
      ],
      price: 2.99,
      image: 'images/fruits/lemon.PNG',
      rating: 4.1,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Mango',
      genus: 'Mangifera',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 15.0},
        {NutritionType.protein: 0.82},
        {NutritionType.fat: 0.38},
        {NutritionType.calories: 60.0},
        {NutritionType.sugar: 13.7},
      ],
      price: 2.59,
      image: 'images/fruits/mango.png',
      rating: 4.7,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Orange',
      genus: 'Citrus',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 8.3},
        {NutritionType.protein: 1.2},
        {NutritionType.fat: 0.2},
        {NutritionType.calories: 43.0},
        {NutritionType.sugar: 8.2},
      ],
      price: 2.29,
      image: 'images/fruits/orange.PNG',
      rating: 4.8,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Papaya',
      genus: 'Carica',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 30.0},
        {NutritionType.protein: 0.0},
        {NutritionType.fat: 0.0},
        {NutritionType.calories: 120.0},
        {NutritionType.sugar: 18.0},
      ],
      price: 9.99,
      image: 'images/fruits/papaya.PNG',
      rating: 4.8,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Pear',
      genus: 'Pyrus',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 15.0},
        {NutritionType.protein: 0.4},
        {NutritionType.fat: 0.1},
        {NutritionType.calories: 57.0},
        {NutritionType.sugar: 10.0},
      ],
      price: 25.99,
      image: 'images/fruits/pear.png',
      rating: 4.8,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Pineapple',
      genus: 'Ananas',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 13.12},
        {NutritionType.protein: 0.54},
        {NutritionType.fat: 0.12},
        {NutritionType.calories: 50.0},
        {NutritionType.sugar: 9.85},
      ],
      price: 9.99,
      image: 'images/fruits/pineapple.PNG',
      rating: 4.7,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Raspberry',
      genus: 'Rubus',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 12.0},
        {NutritionType.protein: 1.2},
        {NutritionType.fat: 0.7},
        {NutritionType.calories: 53.0},
        {NutritionType.sugar: 4.4},
      ],
      price: 11.99,
      image: 'images/fruits/raspberry.png',
      rating: 4.4,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Strawberry',
      genus: 'Fragaria',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 5.5},
        {NutritionType.protein: 0.8},
        {NutritionType.fat: 0.4},
        {NutritionType.calories: 29.0},
        {NutritionType.sugar: 5.4},
      ],
      price: 7.99,
      image: 'images/fruits/strawberry.PNG',
      rating: 4.8,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Tomato',
      genus: 'Solanum',
      category: Category.fruits,
      nutritions: [
        {NutritionType.carbohydates: 3.9},
        {NutritionType.protein: 0.9},
        {NutritionType.fat: 0.2},
        {NutritionType.calories: 74.0},
        {NutritionType.sugar: 2.6},
      ],
      price: 3.99,
      image: 'images/fruits/tomato.PNG',
      rating: 4.3,
    ),

    // Nuts
    Plant(
      id: Uuid.v4(),
      name: 'Almond nuts',
      genus: 'Prunus',
      category: Category.nuts,
      nutritions: [
        {NutritionType.carbohydates: 11.0},
        {NutritionType.protein: 10.0},
        {NutritionType.fat: 24.0},
        {NutritionType.calories: 228.0},
        {NutritionType.sugar: 2.0},
      ],
      price: 0.99,
      image: 'images/nuts/almond-nuts.png',
      rating: 4.6,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Cashew nuts',
      genus: 'Anacardium',
      category: Category.nuts,
      nutritions: [
        {NutritionType.carbohydates: 0.0},
        {NutritionType.protein: 9.0},
        {NutritionType.fat: 14.0},
        {NutritionType.calories: 185.0},
        {NutritionType.sugar: 9.0},
      ],
      price: 10.99,
      image: 'images/nuts/cashew-nuts.png',
      rating: 4.6,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Chestnuts',
      genus: 'Castenea',
      category: Category.nuts,
      nutritions: [
        {NutritionType.carbohydates: 4.0},
        {NutritionType.protein: 1.0},
        {NutritionType.fat: 1.0},
        {NutritionType.calories: 200.0},
        {NutritionType.sugar: 11.0},
      ],
      price: 5.99,
      image: 'images/nuts/chestnuts.png',
      rating: 4.0,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Hazelnuts',
      genus: 'Corylus',
      category: Category.nuts,
      nutritions: [
        {NutritionType.carbohydates: 5.0},
        {NutritionType.protein: 4.0},
        {NutritionType.fat: 17.0},
        {NutritionType.calories: 176.0},
        {NutritionType.sugar: 1.0},
      ],
      price: 12.99,
      image: 'images/nuts/hazelnut.png',
      rating: 4.0,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Peanuts',
      genus: 'Arachis',
      category: Category.nuts,
      nutritions: [
        {NutritionType.carbohydates: 16.0},
        {NutritionType.protein: 25.0},
        {NutritionType.fat: 49.0},
        {NutritionType.calories: 567.0},
        {NutritionType.sugar: 4.0},
      ],
      price: 5.99,
      image: 'images/nuts/peanuts.png',
      rating: 4.6,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Pecan nuts',
      genus: 'Hickory',
      category: Category.nuts,
      nutritions: [
        {NutritionType.carbohydates: 3.0},
        {NutritionType.protein: 2.0},
        {NutritionType.fat: 20.0},
        {NutritionType.calories: 193.0},
        {NutritionType.sugar: 1.0},
      ],
      price: 5.99,
      image: 'images/nuts/pecan-nuts.png',
      rating: 4.0,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Walnuts',
      genus: 'Juglans',
      category: Category.nuts,
      nutritions: [
        {NutritionType.carbohydates: 0.0},
        {NutritionType.protein: 0.0},
        {NutritionType.fat: 2.0},
        {NutritionType.calories: 26.0},
        {NutritionType.sugar: 0.0},
      ],
      price: 2.99,
      image: 'images/nuts/walnuts.png',
      rating: 4.8,
    ),

    // Vegetables
    Plant(
      id: Uuid.v4(),
      name: 'Cabbage',
      genus: 'Cabbages',
      category: Category.vegetables,
      nutritions: [
        {NutritionType.carbohydates: 5.0},
        {NutritionType.protein: 1.0},
        {NutritionType.fat: 0.0},
        {NutritionType.calories: 22.0},
        {NutritionType.sugar: 1.0},
      ],
      price: 0.99,
      image: 'images/vegs/cabbage.PNG',
      rating: 3.6,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Carrot',
      genus: 'Daucus',
      category: Category.vegetables,
      nutritions: [
        {NutritionType.carbohydates: 35.0},
        {NutritionType.protein: 1.0},
        {NutritionType.fat: 0.0},
        {NutritionType.calories: 4.0},
        {NutritionType.sugar: 12.0},
      ],
      price: 0.59,
      image: 'images/vegs/carrot.PNG',
      rating: 4.3,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Lettuce',
      genus: 'Lactuca',
      category: Category.vegetables,
      nutritions: [
        {NutritionType.carbohydates: 0.0},
        {NutritionType.protein: 0.0},
        {NutritionType.fat: 0.0},
        {NutritionType.calories: 25.0},
        {NutritionType.sugar: 0.0},
      ],
      price: 39.99,
      image: 'images/vegs/lettuce.PNG',
      rating: 3.0,
    ),
    Plant(
      id: Uuid.v4(),
      name: 'Parsely',
      genus: 'Petroselinum',
      category: Category.vegetables,
      nutritions: [
        {NutritionType.carbohydates: 6.0},
        {NutritionType.protein: 3.0},
        {NutritionType.fat: 1.0},
        {NutritionType.calories: 36.0},
        {NutritionType.sugar: 3.0},
      ],
      price: 1.99,
      image: 'images/vegs/parsely.PNG',
      rating: 3.2,
    ),
  ];
}
